---
#- name: reboot server into rescue image
#  hosts: hetzner
#  connection: local
#  vars_files:
#  - secrets.yml
#  roles:
#  - role: hetzner-boot-rescue

- name: install debian 9.11 minimal
  hosts: hetzner
  vars_files:
  - secrets.yml
  roles:
  - role: hetzner-install-debain-9.11
    vars:
    # Disable SSH checking, it's mostly useless in this role's use case;
    # not done automatically because of the obvious insecurity
      ansible_ssh_extra_args:
        -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
  
- name: install packages
  hosts: hetzner
  vars_files:
  - secrets.yml
  roles:
  - role: install-packages

- name: final reboot
  hosts: hetzner
  vars_files:
  - secrets.yml
  roles:
  - role: reboot